export type Language = 'EN' | 'TH';

export const translations = {
    EN: {
        menu: {
            HOME: 'HOME',
            PROJECTS: 'PROJECTS',
            ABOUT: 'ABOUT',
            NEWS: 'NEWS',
            CAREERS: 'CAREERS',
            CONTACT: 'CONTACT',
        },
        home: {
            SELECTED_PROJECTS: 'SELECTED PROJECTS',
            VIEW_ALL: 'VIEW ALL',
            NO_PROJECTS: 'No projects yet',
            VIEW_PROJECT_BTN: 'VIEW PROJECT',
            PHILOSOPHY_TITLE: 'OUR PHILOSOPHY',
            PHILOSOPHY_HEADLINE: 'We craft space',
            PHILOSOPHY_HEADLINE_SUB: 'that tells your story.',
            PHILOSOPHY_DESC_1: "At 1931 Design, we believe that architecture is more than just buildings—it's about creating experiences. Every line we draw and every material we choose is guided by a deep understanding of our client's vision.",
            PHILOSOPHY_DESC_2: 'We blend timeless aesthetics with modern functionality to create spaces that inspire, comfort, and endure.',
            SERVICES_SUBTITLE: 'WHAT WE DO',
            SERVICES_TITLE: 'Our Expertise',
            SERVICES_ARCH_TITLE: 'Architecture',
            SERVICES_ARCH_DESC: 'Comprehensive architectural design from concept to construction documents.',
            SERVICES_INTERIOR_TITLE: 'Interior Design',
            SERVICES_INTERIOR_DESC: 'Crafting interior spaces that harmonize with the architectural shell.',
            SERVICES_CONST_TITLE: 'Construction',
            SERVICES_CONST_DESC: 'High-quality construction services ensuring the vision is built to last.',
            SERVICES_RENO_TITLE: 'Renovation',
            SERVICES_RENO_DESC: 'Transforming existing spaces into modern, functional environments.',
            CTA_SUBTITLE: "LET'S WORK TOGETHER",
            CTA_TITLE: 'Have a project in mind?',
            CTA_TITLE_SUB: "Let's build it.",
            CTA_BUTTON: 'START PROJECT',
        },
        about: {
            COMPANY_NAME: '1931 Co., Ltd.',
            DESCRIPTION: "The diversity of our team enables us to create a broad range of architectural and Decoration styles. From modern and striking, to contemporary and traditional. We approach each project differently and believe that each one should have its own distinctive character.",
        },
        projects: {
            TITLE: 'PROJECTS',
            ALL: 'ALL',
            RELATED: 'RELATED PROJECTS',
            NO_PROJECTS_FOUND: 'No projects found in this category.',
            VIEW_DETAILS: 'VIEW DETAILS',
            LOADING: 'Loading projects...',
            VIEW_GALLERY: 'VIEW GALLERY',
            DESCRIPTION: 'PROJECT DESCRIPTION',
            OWNER: 'OWNER',
            LOCATION: 'LOCATION',
            STATUS: 'STATUS',
            VIEW_MAP: 'View on Map',
            GALLERY: 'GALLERY',
            NO_DESCRIPTION: 'No description available.',
        },
        contact: {
            TITLE: 'CONTACT',
            HEADQUARTERS: 'HEADQUARTERS',
            CAREERS: 'CAREERS',
            SEND_MESSAGE: 'SEND US A MESSAGE',
            NAME: 'NAME',
            EMAIL: 'EMAIL',
            SUBJECT: 'SUBJECT',
            MESSAGE: 'MESSAGE',
            SEND: 'SEND MESSAGE',
            SUCCESS: 'Message sent successfully!',
            ERROR: 'Failed to send message. Please try again.',
            SENDING: 'Sending...',
            REQUIRED: 'Required',
            MESSAGE_HINT: '(Minimum 10 characters)',
            MAP_LABEL: 'Google Map',
        },
        footer: {
            RIGHTS: 'ALL RIGHTS RESERVED.',
        },
    },
    TH: {
        menu: {
            HOME: 'หน้าแรก',
            PROJECTS: 'ผลงาน',
            ABOUT: 'เกี่ยวกับเรา',
            NEWS: 'ข่าวสาร',
            CAREERS: 'ร่วมงานกับเรา',
            CONTACT: 'ติดต่อเรา',
        },
        home: {
            SELECTED_PROJECTS: 'ผลงานที่คัดสรร',
            VIEW_ALL: 'ดูทั้งหมด',
            NO_PROJECTS: 'ยังไม่มีโปรเจกต์',
            VIEW_PROJECT_BTN: 'ดูโปรเจกต์',
            PHILOSOPHY_TITLE: 'ปรัชญาของเรา',
            PHILOSOPHY_HEADLINE: 'เราสร้างสรรค์พื้นที่',
            PHILOSOPHY_HEADLINE_SUB: 'ที่บอกเล่าเรื่องราวของคุณ',
            PHILOSOPHY_DESC_1: 'ที่ 1931 Design เราเชื่อว่าสถาปัตยกรรมเป็นมากกว่าแค่อาคาร—คือการสร้างประสบการณ์ ทุกเส้นสายที่เราวาดและทุกวัสดุที่เราเลือก ได้รับการชี้นำด้วยความเข้าใจอย่างลึกซึ้งในวิสัยทัศน์ของลูกค้า',
            PHILOSOPHY_DESC_2: 'เราผสมผสานความงามเหนือกาลเวลาเข้ากับฟังก์ชันการใช้งานที่ทันสมัย เพื่อสร้างพื้นที่ที่สร้างแรงบันดาลใจ ความสะดวกสบาย และคงทนถาวร',
            SERVICES_SUBTITLE: 'สิ่งที่เราทำ',
            SERVICES_TITLE: 'ความเชี่ยวชาญของเรา',
            SERVICES_ARCH_TITLE: 'งานสถาปัตยกรรม',
            SERVICES_ARCH_DESC: 'การออกแบบสถาปัตยกรรมแบบครบวงจร ตั้งแต่แนวคิดจนถึงเอกสารการก่อสร้าง',
            SERVICES_INTERIOR_TITLE: 'งานออกแบบภายใน',
            SERVICES_INTERIOR_DESC: 'สร้างสรรค์พื้นที่ภายในที่กลมกลืนกับโครงสร้างสถาปัตยกรรม',
            SERVICES_CONST_TITLE: 'งานก่อสร้าง',
            SERVICES_CONST_DESC: 'บริการก่อสร้างคุณภาพสูง เพื่อให้มั่นใจว่าวิสัยทัศน์ถูกสร้างขึ้นให้คงอยู่ยาวนาน',
            SERVICES_RENO_TITLE: 'งานรีโนเวท',
            SERVICES_RENO_DESC: 'เปลี่ยนพื้นที่เดิมให้เป็นสภาพแวดล้อมที่ทันสมัยและใช้งานได้จริง',
            CTA_SUBTITLE: 'ร่วมงานกับเรา',
            CTA_TITLE: 'สนใจเริ่มโปรเจกต์?',
            CTA_TITLE_SUB: 'มาสร้างให้เป็นจริงกัน',
            CTA_BUTTON: 'เริ่มโครงการ',
        },
        about: {
            COMPANY_NAME: 'บริษัท 1931 จำกัด',
            DESCRIPTION: 'ความหลากหลายของทีมเราทำให้เราสามารถสร้างสรรค์สไตล์สถาปัตยกรรมและการตกแต่งที่หลากหลาย ตั้งแต่ทันสมัยและโดดเด่น ไปจนถึงร่วมสมัยและดั้งเดิม เราเข้าถึงแต่ละโปรเจกต์ด้วยมุมมองที่แตกต่าง และเชื่อว่าแต่ละงานควรมีเอกลักษณ์เฉพาะตัว',
        },
        projects: {
            TITLE: 'ผลงาน',
            ALL: 'ทั้งหมด',
            RELATED: 'ผลงานที่เกี่ยวข้อง',
            NO_PROJECTS_FOUND: 'ไม่พบโปรเจกต์ในหมวดหมู่นี้',
            VIEW_DETAILS: 'ดูรายละเอียด',
            LOADING: 'กำลังโหลดโปรเจกต์...',
            VIEW_GALLERY: 'ดูรูปภาพทั้งหมด',
            DESCRIPTION: 'รายละเอียดโครงการ',
            OWNER: 'เจ้าของโครงการ',
            LOCATION: 'สถานที่ตั้ง',
            STATUS: 'สถานะ',
            VIEW_MAP: 'ดูแผนที่',
            GALLERY: 'แกลเลอรี',
            NO_DESCRIPTION: 'ไม่มีรายละเอียด',
        },
        contact: {
            TITLE: 'ติดต่อเรา',
            HEADQUARTERS: 'สำนักงานใหญ่',
            CAREERS: 'ร่วมงานกับเรา',
            SEND_MESSAGE: 'ส่งข้อความถึงเรา',
            NAME: 'ชื่อ',
            EMAIL: 'อีเมล',
            SUBJECT: 'หัวข้อ',
            MESSAGE: 'ข้อความ',
            SEND: 'ส่งข้อความ',
            SUCCESS: 'ส่งข้อความเรียบร้อยแล้ว!',
            ERROR: 'ส่งข้อความไม่สำเร็จ กรุณาลองใหม่อีกครั้ง',
            SENDING: 'กำลังส่ง...',
            REQUIRED: 'จำเป็น',
            MESSAGE_HINT: '(อย่างน้อย 10 ตัวอักษร)',
            MAP_LABEL: 'แผนที่กูเกิล',
        },
        footer: {
            RIGHTS: 'สงวนลิขสิทธิ์',
        },
    },
};

export const categories = [
    {
        id: 1,
        name: 'Architecture',
    },
    {
        id: 2,
        name: 'Interior',
    },
    {
        id: 3,
        name: 'Built-in',
    },
    {
        id: 4,
        name: 'Renovate',
    },
    {
        id: 5,
        name: 'Landscape',
    },
    {
        id: 6,
        name: 'Construction',
    },
];

export const projects = [
    {
        id: 1,
        title: 'บ้านพักตากอากาศ, ท่าเทียบเรือ',
        location: 'บ้านโพธิ์ จ.ฉะเชิงเทรา',
        categoryId: '1',
        category: 'Architecture',
        image: '/images/projects/1/S__5087275.jpg',
        description:
            'บ้านพักตากอากาศ, ท่าเทียบเรือ',
        year: '2024',
        gallery: [
            '/images/projects/1/S__5087275.jpg',
            '/images/projects/1/S__5087276.jpg',
            '/images/projects/1/S__5087277.jpg',
            '/images/projects/1/S__5087278.jpg',
        ],
        owner: 'คุณพรทิวา นิพาริน',
        status: 'Completed',
    },
    {
        id: 2,
        title: 'โรงภาพยนตร์',
        location: 'กรุงเทพมหานคร',
        categoryId: '2',
        category: 'Interior',
        image: '/images/projects/2/S__5087309.jpg',
        description:
            'โรงภาพยนตร์',
        year: '2023',
        gallery: ['/images/projects/2/S__5087309.jpg', '/images/projects/2/S__5087310.jpg'],
        owner: 'คุณพรทิวา นิพาริน',
        status: 'Completed',
    },
    // {
    //     id: 3,
    //     title: 'URBAN OASIS',
    //     location: 'CHIANG MAI',
    //     category: 'RESIDENTIAL',
    //     image: '/images/slide3.png',
    //     description:
    //         'Modern residential complex focusing on green spaces and community living in the urban context.',
    //     year: '2024',
    //     gallery: ['/images/slide3.png', '/images/slide1.png', '/images/slide2.png'],
    // },
    // {
    //     id: 4,
    //     title: 'RIVERSIDE RESIDENCE',
    //     location: 'BANGKOK',
    //     category: 'RESIDENTIAL',
    //     image: '/images/slide2.png',
    //     description:
    //         'Exclusive waterfront residences offering panoramic views of the Chao Phraya River.',
    //     year: '2022',
    //     gallery: ['/images/slide2.png', '/images/slide1.png'],
    // },
    // {
    //     id: 5,
    //     title: 'KNOWLEDGE CENTER',
    //     location: 'KHON KAEN',
    //     category: 'EDUCATION',
    //     image: '/images/slide1.png',
    //     description:
    //         'A modern educational facility designed to foster collaboration and innovation.',
    //     year: '2023',
    //     gallery: ['/images/slide1.png', '/images/slide3.png'],
    // },
    // {
    //     id: 6,
    //     title: 'CITY HUB',
    //     location: 'BANGKOK',
    //     category: 'COMMERCIAL',
    //     image: '/images/slide3.png',
    //     description: 'Mixed-use commercial hub connecting transit, retail, and office spaces.',
    //     year: '2025',
    //     gallery: ['/images/slide3.png', '/images/slide2.png', '/images/slide1.png'],
    // },
];

export const news = [
    {
        id: 1,
        date: 'NOV 20, 2025',
        title: '1931 WINS BEST DESIGN AWARD 2025',
        category: 'AWARDS',
        image: '/images/slide1.png',
        content:
            "We are honored to receive the Best Design Award 2025 for our work on the Skyline Tower project. This recognition reflects our commitment to excellence and innovation in architectural design. The jury praised the project's integration of sustainable technologies and its positive impact on the urban fabric.",
    },
    {
        id: 2,
        date: 'OCT 15, 2025',
        title: 'SKYLINE TOWER GRAND OPENING',
        category: 'EVENTS',
        image: '/images/slide2.png',
        content:
            "The Skyline Tower officially opened its doors today, marking a new chapter in Bangkok's architectural landscape. The ceremony was attended by city officials and industry leaders. The tower stands as a testament to modern engineering and design.",
    },
    {
        id: 3,
        date: 'SEP 01, 2025',
        title: 'NEW SUSTAINABLE DESIGN INITIATIVE',
        category: 'NEWS',
        image: '/images/slide3.png',
        content:
            '1931 Co., Ltd. is proud to announce a new initiative focused on sustainable design practices. We are committing to reducing the carbon footprint of all our future projects by 30% over the next five years through the use of eco-friendly materials and energy-efficient systems.',
    },
    {
        id: 4,
        date: 'AUG 10, 2025',
        title: 'LECTURE AT BANGKOK DESIGN WEEK',
        category: 'EVENTS',
        image: '/images/slide1.png',
        content:
            'Our lead architect gave a keynote lecture at Bangkok Design Week, discussing the future of urban living and the role of architecture in shaping resilient communities. The talk was well-received and sparked interesting discussions among attendees.',
    },
];

export const careers = [
    {
        id: 1,
        title: 'SENIOR ARCHITECT',
        type: 'FULL TIME',
        location: 'BANGKOK',
        description:
            'We are looking for an experienced Senior Architect to lead design projects from concept to completion.',
        responsibilities: [
            'Lead architectural design projects and teams.',
            'Coordinate with clients, consultants, and contractors.',
            'Ensure design quality and compliance with regulations.',
            'Mentor junior staff.',
        ],
        requirements: [
            "Bachelor's or Master's degree in Architecture.",
            'Minimum 8 years of experience.',
            'Proficiency in Revit, AutoCAD, and SketchUp.',
            'Strong leadership and communication skills.',
        ],
    },
    {
        id: 2,
        title: 'INTERIOR DESIGNER',
        type: 'FULL TIME',
        location: 'BANGKOK',
        description:
            'Creative Interior Designer needed to craft inspiring interior spaces for high-end residential and commercial projects.',
        responsibilities: [
            'Develop interior design concepts and mood boards.',
            'Select materials, furniture, and lighting.',
            'Produce detailed drawings and specifications.',
            'Collaborate with architects and contractors.',
        ],
        requirements: [
            'Degree in Interior Design or related field.',
            'Minimum 3 years of experience.',
            'Strong portfolio demonstrating creative ability.',
            'Knowledge of materials and construction details.',
        ],
    },
    {
        id: 3,
        title: 'JUNIOR ARCHITECT',
        type: 'FULL TIME',
        location: 'PHUKET',
        description:
            'Opportunity for a motivated Junior Architect to join our Phuket office and work on exciting hospitality projects.',
        responsibilities: [
            'Assist in design development and documentation.',
            'Create 3D models and renderings.',
            'Prepare presentation materials.',
            'Support senior architects in project coordination.',
        ],
        requirements: [
            'Degree in Architecture.',
            '1-3 years of experience.',
            'Proficiency in 3D modeling software.',
            'Eager to learn and grow.',
        ],
    },
    {
        id: 4,
        title: 'DRAFTSMAN',
        type: 'CONTRACT',
        location: 'BANGKOK',
        description:
            'Skilled Draftsman required to assist in the production of technical drawings and construction documents.',
        responsibilities: [
            'Produce accurate technical drawings.',
            'Update drawings based on feedback.',
            'Ensure adherence to drafting standards.',
            'Assist in site measurements.',
        ],
        requirements: [
            'Diploma or Certificate in Drafting or Architecture.',
            'Proficiency in AutoCAD.',
            'Attention to detail and accuracy.',
            'Ability to meet deadlines.',
        ],
    },
];

export const careersMock = [
    {
        id: 1,
        title: 'SENIOR ARCHITECT',
        type: 'FULL TIME',
        location: 'BANGKOK',
        description:
            'We are looking for an experienced Senior Architect to lead design projects from concept to completion.',
        responsibilities: [
            'Lead architectural design projects and teams.',
            'Coordinate with clients, consultants, and contractors.',
            'Ensure design quality and compliance with regulations.',
            'Mentor junior staff.',
        ],
        requirements: [
            "Bachelor's or Master's degree in Architecture.",
            'Minimum 8 years of experience.',
            'Proficiency in Revit, AutoCAD, and SketchUp.',
            'Strong leadership and communication skills.',
        ],
    },
    {
        id: 2,
        title: 'INTERIOR DESIGNER',
        type: 'FULL TIME',
        location: 'BANGKOK',
        description:
            'Creative Interior Designer needed to craft inspiring interior spaces for high-end residential and commercial projects.',
        responsibilities: [
            'Develop interior design concepts and mood boards.',
            'Select materials, furniture, and lighting.',
            'Produce detailed drawings and specifications.',
            'Collaborate with architects and contractors.',
        ],
        requirements: [
            'Degree in Interior Design or related field.',
            'Minimum 3 years of experience.',
            'Strong portfolio demonstrating creative ability.',
            'Knowledge of materials and construction details.',
        ],
    },
    {
        id: 3,
        title: 'JUNIOR ARCHITECT',
        type: 'FULL TIME',
        location: 'PHUKET',
        description:
            'Opportunity for a motivated Junior Architect to join our Phuket office and work on exciting hospitality projects.',
        responsibilities: [
            'Assist in design development and documentation.',
            'Create 3D models and renderings.',
            'Prepare presentation materials.',
            'Support senior architects in project coordination.',
        ],
        requirements: [
            'Degree in Architecture.',
            '1-3 years of experience.',
            'Proficiency in 3D modeling software.',
            'Eager to learn and grow.',
        ],
    },
    {
        id: 4,
        title: 'DRAFTSMAN',
        type: 'CONTRACT',
        location: 'BANGKOK',
        description:
            'Skilled Draftsman required to assist in the production of technical drawings and construction documents.',
        responsibilities: [
            'Produce accurate technical drawings.',
            'Update drawings based on feedback.',
            'Ensure adherence to drafting standards.',
            'Assist in site measurements.',
        ],
        requirements: [
            'Diploma or Certificate in Drafting or Architecture.',
            'Proficiency in AutoCAD.',
            'Attention to detail and accuracy.',
            'Ability to meet deadlines.',
        ],
    },
];
